coreproject-moe/CoreProject

frontend/src/routes/__layout.svelte, frontend/src/routes/anime/[slug].svelte
=> Finish layout.

frontend/src/routes/__layout.svelte, frontend/src/routes/anime/[slug].svelte
=> Add White text

frontend/src/routes/__layout.svelte, frontend/src/routes/anime/[slug].svelte, frontend/src/routes/anime/index.svelte
=> Add new layout

AnimeCore/backend/api/v1/capture/views.py, AnimeCore/backend/api/v1/user/serializers.py, AnimeCore/backend/api/v1/user/urls.py, AnimeCore/backend/api/v1/user/views.py, AnimeCore/backend/core/settings.py, AnimeCore/backend/core/urls.py, AnimeCore/backend/custom/users/admin.py, AnimeCore/backend/custom/users/models.py
=> Add Register Page Endpoint

AnimeCore/backend/api/v1/user/views.py, AnimeCore/frontend/src/lib/constants/backend/urls/restEndpoints.ts, AnimeCore/frontend/src/routes/user/logout.svelte, AnimeCore/frontend/src/routes/user/register.svelte
=> Finish `Register`

backend/Pipfile.lock, backend/apps/anime/views/anime_recommendation.py
This reverts commit a55c2b895ba033305022340c7ded16b751b6b36d.
=> Revert "Update anime_recommendation.py"

frontend/AnimeCore/components/swiper/MainHero.tsx, frontend/AnimeCore/package-lock.json, frontend/AnimeCore/package.json
=> [ `Frontend` ] : Add skeleton

backend/django_core/apps/api/filters/anime.py, backend/django_core/apps/api/filters/characters.py, backend/django_core/apps/api/filters/producers.py, backend/django_core/apps/api/filters/staffs.py, backend/django_core/apps/api/filters/studios.py, frontend/User/tailwind.config.cjs
=> [`Backend`] : Fix broken Backend

backend/django_core/core/settings.py, backend/django_core/core/urls.py, backend/django_core/core/views.py, backend/django_core/templates/errors/base.html, backend/django_core/templates/home/index.html, backend/django_core/templates/tailwind_base.html
Credit  : https://codepen.io/Hyperplexed/full/MWQeYLW
Youtube : https://www.youtube.com/watch?v=htGfnF1zN4g&feature=youtu.be
=> [`Backend`] :  Add Magical Hover effect

tools/seeder/scraper/models.py, tools/seeder/scraper/scrapers.py, tools/seeder/scraper/test.py
=> [`Tools`] : Anime Info scraper

backend/django_core/apps/api/views/anime/anime_genre.py, backend/django_core/apps/api/views/anime/anime_producer.py, backend/django_core/apps/api/views/anime/anime_studio.py, backend/django_core/apps/api/views/anime/anime_theme.py
Now that we allow patch methods. We can actually remove these code
=> [`Backend`] : Remove post methods

README.md
Updated readme with v3 UI screenshots and links.
=> [ `Enhancement` ] : Update README

backend/django_core/templates/anime/info/index.html
=> refactor: move to `scroll-area` component

backend/components/text_editor/text_editor.html, backend/django_core/static_src/js/texteditor.ts
Some text editor refactoring...
=> [`Backend`]: refactor textarea codes

backend/django_core/static_src/functions/format_date.ts, backend/package-lock.json, backend/package.json
=> Port to date fns

backend/django_core/templates/anime/_layout.html
Lookup : https://tailwindcss.com/blog/tailwindcss-v3-4#dynamic-viewport-units
=> [`Frontend`] : Update to latest feature `dvh`

backend/django_core/static_src/components/specific/LatestEpisodes/Index.svelte, backend/package-lock.json, backend/package.json
Python dictionaries are best serialized as `JSON5`
=> [`Frontend`] ; Move to `json5`

backend/django_core/static_src/components/page/explore/AnimeCard.svelte, backend/django_core/static_src/components/page/explore/Index.svelte
=> [`Frontend`]: Fix Explore page issue

backend/django_core/templates/anime/_layout.html, backend/django_core/templates/anime/_slider.html, backend/django_core/templates/anime/index.html
* fix: _layout header
* fix: _slider
* fix: footer
* fix: my_list section minor style issue
=> [`Frontend`]: fix: `Index` page

backend/django_core/static_src/components/page/anime/info/Index.svelte
=> Logic should be as pretty as a fish

backend/django_core/apps/api/views/comment/__init__.py
When deleting comment, we destroy all the childrens in it
=> Delete childrens when deleting parent comment

backend/django_core/apps/gql/functions/dictionary.py, backend/django_core/apps/gql/input/user.py, backend/django_core/apps/gql/mutations/anime.py, backend/django_core/apps/gql/mutations/user.py, backend/django_core/apps/gql/schema.py, backend/django_core/apps/gql/types/token.py, backend/django_core/apps/gql/types/user.py, backend/django_core/apps/gql/views.py
Blocked by:
- https://github.com/strawberry-graphql/strawberry-django/issues/507
=> Graphql Work on users

backend/django_core/static_src/components/page/home/Index.svelte, backend/django_core/static_src/components/specific/UserForm/Register/Forms/1.svelte
This PR improves the responsiveness of the website by about 25%
=> [`Frontend`] : Improve code loading

.github/workflows/seeder-build.yml
:warning: **UPVOTE THIS**
https://github.com/orgs/community/discussions/11831
=> chore: namespace actions

seeder/src/seeder_flet/lib/views/login.py
=> refactor: seeder login to async with asyncio

seeder/.husky/pre-commit, seeder/package-lock.json, seeder/package.json
NO MORE extra necessary format commits!!
=> [seeder] Feat: add husky

seeder/src/renderer/components/sidebar/index.tsx, seeder/src/renderer/constants/commands.ts, seeder/src/renderer/constants/shiinobi.ts, seeder/src/renderer/main.tsx, seeder/src/renderer/routes/home/index.tsx
Support `PLATFORMS` and new commands logic
=> refactor(seeder): workflow with new shiinobi version

seeder/package-lock.json, seeder/package.json
Reverts coreproject-moe/CoreProject#4252
=> Revert "chore(deps-dev): bump electron from 32.2.0 to 33.0.2 in /seeder"

tracker/frontend/src/components/navbar.tsx
=> feat: Add background behind coreproject logo

tracker/backend/coreproject_tracker/functions/redis.py, tracker/backend/coreproject_tracker/servers/http.py, tracker/backend/coreproject_tracker/servers/udp.py, tracker/backend/coreproject_tracker/servers/websocket.py
So far my search has told me that webtorrent doesn't support hybrid trackers, so separate it unless explicitly requested
=> Seperate the data by type
